### ISSUE TITLE
Migrate Jupyter Utilities from Javis to JavisNB

### ISSUE THREAD

**Issue by TheCedarPrince** [JuliaAnimators/JavisNB.jl#1]
**Is your feature request related to a problem? Please explain.**

Currently, Javis has Jupyter + Interact utilities inside of the package.
It would be best to move those out to JavisNB.

**Describe the solution you'd like**

Move the lines starting here: https://github.com/JuliaAnimators/Javis.jl/blob/bc65d7a29fcf80e92b08b2455e699d65b822f718/src/javis_viewer.jl#L241

Pertaining to Jupyter to JavisNB!
Make sure to also migrate the tests as well! 

Steps:

- [ ] Migrate Jupyter utilities
- [ ] Create tests
- [ ] Add documentation

**Describe alternatives you've considered**

N/A

**Additional context**

Based on a conversation with @gpucce

**Comment by gpucce** [comment]
Hi @TheCedarPrince I hope I will manage to do this things in a reasonable time! 

I have one question first of all, do we want someone to write using JavisNB when working in a notebook or should Javis have this package as a dependency?

**Comment by Wikunia** [comment]
I think we want that a user needs to write `using JavisNB` as this makes compilation faster and then the dependencies are uncoupled such that adding Javis has fewer possibilities to fail

**Comment by TheCedarPrince** [comment]
Fully agree with @Wikunia .
That is what I imagine where a series of used packages could look like in use:

```julia
using Javis
using JavisNB
```

Where `Javis` is expected as a dependency of `JavisNB` but `JavisNB` is not a dependency of `Javis`.
I also do not expect that `JavisNB` export any functionality from `Javis` itself but rather utilizes `Javis` for the functions that `JavisNB` will export.

And no worries about reasonable time @gpucce !
I certainly was a bit delayed between vaccine booster shot and American holidays in getting this repository going!
