### ISSUE TITLE
Deploy Documentation via Documenter.jl

### ISSUE THREAD

**Issue by TheCedarPrince** [JuliaAnimators/JavisNB.jl#3]
**Is your feature request related to a problem? Please explain.**

Currently, the CI script in workflows, does not deploy docs yet.
This is not great as we need docs!

**Describe the solution you'd like**

I would like to have the Documentation up and running with documenter showing how one can interact with notebooks.
I don't think it needs to be too complicated as there may not be too much to show for this package at the moment.
If you need assistance myself or @Wikunia can advise!

**Describe alternatives you've considered**

Docstrings!

**Additional context**

Based on conversation with @gpucce several weeks ago.

**Comment by Wikunia** [comment]
I assume uncommenting these: https://github.com/JuliaAnimators/JavisNB/blob/main/.github/workflows/ci.yml#L46-L64 might help :smile: 
Not sure whether we need to set a key as well. Haven't checked whether you already did.

**Comment by TheCedarPrince** [comment]
Haha, yes @Wikunia !
But also just setting up the docs folder, config, etc. Still need to be set.
Hadn't gotten to that just yet.

**Comment by TheCedarPrince** [comment]
@gpucce - the docs have been successfully deployed!
Had to enable something in organization settings but the docs are deployed now!
